yangshun/front-end-interview-handbook

README.md
Answers ES6 destructuring question lightly, with a few examples both of Array and Object destructuring.
=> Answer JS destructuring question

questions/css-questions.md
Referred to question:
https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/css-questions.md#can-you-give-an-example-of-an-media-property-other-than-screen
=> Answer to @media types' question with example

questions/javascript-questions.md
Should be `Function.prototype.bind` instead of `Array.prototype.bind`
=> Fix typo in answer

README.md
When we translate and put them in /Translations, relative paths do not work well.
So, how about to use absolute ones even in original README.md?
And I added links to original(English) link mainly the purpose from translations.
=> how about using absolute path in README.md?

questions/javascript-questions.md
I believe it is a key characteristic between undefined variables and null variables, that being that typeof null evaluates to `object` while this same isn't true for undefined variables.
=> Adds typeof example for null values

Translations/Chinese/questions/css-questions.md
In CSS question `How do you serve your pages for feature-constrained browsers? What techniques/processes do you use?`
list item 2 is translated but original words are still left in English, got duplicated.
Just got it removed.
=> Fix a translation problem in Chinese

questions/html-questions.md
Found and fixed a typo in front-end-interview-handbook/questions/html-questions.md on line 24.
Original word - declation.
Changed to - declaration.
=> Fixed a typo in HTML questions. Fixes issue #150

questions/html-questions.md
I fixed a minor typo in the answer to the multilingual sites question. Previously it said:
```
each string of text will need to have it's a separate image created for each language.
```
I removed the word "it's" so that it now just reads as:
```
each string of text will need to have a separate image created for each language.
```
=> [HTML] Fix a minor typo

questions/javascript-questions.md
This pull request fixes a typo I made in a contribution to this question: [What language constructions do you use for iterating over object properties and array items?](https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#what-language-constructions-do-you-use-for-iterating-over-object-properties-and-array-items)
I meant to write that the advantage of the *`for`* loop is that you can break from it. 
BEFORE
The advantage of the _**`for-of`**_ loop is that you can break from it, and the advantage of forEach() is that it is more concise than the for loop because you don't need a counter variable. With the for-of loop, you get both the ability to break from a loop and a more concise syntax. 
AFTER
The advantage of the _**`for`**_ loop is that …
=> [JS] Fix typo

questions/css-questions.md
Just adding a link in the `Explain how a browser determines what elements match a CSS selector` section that references the `What are some of the "gotchas" for writing efficient CSS?` section.
=> [CSS] Add links to browser matching CSS selector section

questions/html-questions.md
* Fix typo ^design^designing in the link in TOC
* SVG text is perfectly scalable and an exception to this rule. I think specifying raster based images takes care of that exception to the rule.
=> [HTML] Fix typo

questions/css-questions.md
… a block formatting context is established is paramount to a front end developer.
It's important to mention the number one reason that knowledge of how a block formatting context is established is paramount to a front end developer.
=> [CSS] Mention why BFC is important

questions/css-questions.md
Discuss presentational attributes being overridable by externally defined CSS. This is an important concept to understand for SVG specifically, since it's counterintuitive that something defined in an attribute has less specificity then outside CSS.
=> [CSS] Mention presentational attribute specificity vs. CSS in SVG question

Translations/Korean/questions/css-questions.md
Hi @yangshun .
thank you for made this repository :)
I changed '자식이 부모보다 크기가 경우' -> '자식이 부모보다 크기가 큰 경우'
For the original document, It is same 'the children is than the parent' -> 'the children is taller than the parent'.
please consider to this pr. and have a nice day!
=> [CSS][KR] fix a typo in CSS question

questions/css-questions.md
The answer to this question lists visibility: hidden. visibility: hidden; hides content from screen readers, so it should be excluded from the list.
https://github.com/yangshun/front-end-interview-handbook/issues/241
=> [css] remove incorrect "visibility: hidden" answer from visually hide content question

questions/css-questions.md
This is a proposal for removing the last phrase of the question "Describe pseudo-elements and discuss what they are used for."
The aforementioned phrase is "It's not really possible to draw a triangle with just CSS styles without using an additional HTML element.". It is easy and totally fine to "draw" any shape by using the CSS "content" property of the before/after pseudo elements. This is why I believe that it is a little bit "misleading".
This technique serves what is mentioned in the answer "Encourages separation of concerns because the triangle is considered part of styling and not really the DOM".
A reference with a list of shapes can be found here: https://css-tricks.com/the-shapes-of-css/
Note: you do not have to add an empty html element and style it to draw a shape. You can …
=> [css] delete misleading statement in pseudo-elements question

questions/javascript-questions.md
Fixed issue found in [Explain how prototypal inheritance works](https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#explain-how-prototypal-inheritance-works) answer.
Actually, answer describes how the `__proto__` works. Unlike `__proto__`, `prototype` is a constructor function's property, which determines the inheritance chain.
[stackoverflow](https://stackoverflow.com/a/9959753)
[w3c](https://www.w3schools.com/js/js_object_prototypes.asp)
=> [js] fix prototypal inheritance question from "prototype" to "__proto__"

contents/en/javascript-questions.md
Removed redundant [url link](http://theproactiveprogrammer.com/javascript/the-javascript-event-loop-a-stack-and-a-queue/) for this [question](https://yangshun.github.io/front-end-interview-handbook/en/javascript-questions/#what-is-event-loop-what-is-the-difference-between-call-stack-and-task-queue). It's no longer available in the web.
=> Remove redundant url link

website/src/pages/index.js
this little PR fix style in Github starts logo.
Before:
After:
=> website: fix style in GitHub stars in home page

README.md
The hyperlink to JavaScript Utility Function Questions in the README has an extra character.
=> fix: broken utility function link in README.md

packages/quiz/questions/describe-event-bubbling/en-US.mdx
Added information on how to prevent event bubbling to help with related follow up questions.
=> qns(quiz): describe how to prevent event bubbling

packages/quiz/questions/explain-how-prototypal-inheritance-works/en-US.mdx
Using Object.create to inherit prototype is a legacy method according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain 
Because it removes the dog constructor and the output will show `The Animal makes a sound` instead of `The Dog makes a sound`
=> fix(quiz): change to the correct way to inherit using prototype

packages/quiz/questions/designing-or-developing-for-multilingual-sites/en-US.mdx
When developing a multilingual website, Google suggests adding an "x-default" link as an option when the user's browser default language is not supported by the website. [Reference here](https://developers.google.com/search/docs/specialty/international/localized-versions#all-method-guidelines).
This PR is a suggestion to add this recommendation to the "designing-or-developing-for-multilingual-sites" quiz.
=> quiz: add x-default suggestion to design or develop multilingual

packages/quiz/questions/what-tools-and-techniques-do-you-use-for-debugging-javascript-code/en-US.mdx
Replace the broken link in en-US.mdx with a blog post written by the same guy on the same topic. The previous link was leading to the hackernoon homepage.
=> qns(quiz): Fix broken link in en-US.mdx

packages/quiz/questions/what-are-the-differences-between-variables-created-using-let-var-or-const/en-US.mdx
The current answer might give the idea that another difference between declaring variables with `var` vs `let` and `const` is that only `var` declared variables are hoisted. 
I think the answer should clarify better that `let` and `const` declared variables are also hoisted but they throw an error because they haven't been initialised yet.
=> fix(quiz): Update en-US.mdx

contents/companies/linkedin-front-end-interview-questions.md
The coding question was incorrectly labeled as Free. I was able to confirm the state by navigating to the question's URL through the hyperlink.
=> contents(company): update LinkedIn question tagging

packages/quiz/questions/why-is-extending-built-in-javascript-objects-not-a-good-idea/en-US.mdx, packages/quiz/questions/why-is-it-in-general-a-good-idea-to-leave-the-global-scope-of-a-website-as-is-and-never-touch-it/en-US.mdx
This change will add details for following quizzes
* Avoid extension of built-in js objects
* Why is it good practice not to pollute global scope
=> quiz/js: avoid global scope pollution and extension of built-in js objects

contents/javascript-questions.md
I fixed a reference link that pointed to a moved Raygun blog post (which now results in a 404) to https://raygun.com/learn/javascript-debugging-tips
=> contents: fix broken link in debugging section

packages/quiz/questions/whats-the-difference-between-inline-and-inline-block/en-US.mdx
- Updated the table with a "Use Cases" row to make it easier for beginners to understand when to use each type.
- Simplified explanations with relatable examples like buttons, text, and page sections.
=> quiz/css: add "Use Cases" row to the display property comparison table

packages/front-end-interview-guidebook/contents/algorithms/en-US.mdx, packages/front-end-interview-guidebook/contents/coding/en-US.mdx, packages/front-end-interview-guidebook/contents/javascript/en-US.mdx, packages/front-end-interview-guidebook/contents/overview/en-US.mdx, packages/front-end-interview-guidebook/contents/quiz/en-US.mdx, packages/front-end-interview-guidebook/contents/system-design/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface-components-api-design-principles/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface-questions-cheatsheet/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface/en-US.mdx
Here are my following changes in the English files of frontend interview playbook:
- Update broken links to correct format
- Replace broken external links with correct ones
=> contents: update and replace broken links in the English files of frontend interview playbook

website/i18n/zh-CN/docusaurus-plugin-content-docs/current/javascript-questions.md
There are some origin en texts which untranslated in zh-CN translations. Remove it for fix.
=> fix: Delete the useless en origin texts in zh-CN translation.

contents/resume.md
Update the Resume preparation page the link to the worded resume link was broken with solving the problem #472
=> fix: update broken link for ATS

contents/resume.md
Originally the link was written with incorrect markdown syntax, nesting two links inside a top-level `[]()`, clicking on which would lead to a 404. I assume the previous editor wanted to showcase both sources of checking your resume (one gives ATS score, another lets you know how well your resume can be parsed) so updated the markdown to show both links
=> [feih] contents/resume: fix broken link in "Resume Preparation" page

website/src/components/SidebarAd/styles.module.css
Problem
Safari showed sharp corners instead of rounded borders on the gradient animations, while Chrome/Firefox worked fine.
Fix
Moved the gradient background to a ::before pseudo-element. Safari handles gradients better when they're on a separate layer from the content.
**Special Notes**
While there isn't any regression in Chrome/Firefox, Firefox's spotlight ad seems to be static while in Chrome/Safari there is animation.
=> [feih] fix: resolve gfe spotlight ad issue on safari

website/blog/2021-08-30-a-glimpse-into-front-end-interviews.md
Fixed Canonical points to redirect issue from Ahrefs
`https://lik.ai/blog/a-glimpse-into-front-end-interviews` now redirects to `https://lik.ai/blog/a-glimpse-into-front-end-interviews/`
Updated the canonical link accordingly
=> [feih] seo: fix canonical points to redirect

website/blog/2021-08-30-a-glimpse-into-front-end-interviews.md, website/docusaurus.config.js
As 4/5 of the blog posts on FEIH have canoical links & are included in the sitemap, various slugs have flagged the issue of Non-canonical page in sitemap
1) /blog
2) /blog/[blog-post]
3) /blog/tags/[tag]
**Fix**
Remove affected `/blog` slugs in sitemap
**Special Notes**
There is one post for "Front End vs. Back End System Design Interviews" that does not have a canonical link, which will stay in the sitemap. Hence, a blanket `/blog/**` wasn't used
=> [feih} seo: fix non canonical page in sitemap issue
