README.md
`DOCTYPE` does not affect HTML parsing. It affects the rendering of the page.
=> Correct `DOCTYPE` section

README.md
Corrected a minor typo in CSS section question 'What's the difference between "resetting" and "normalizing" CSS? Which would you choose, and why?'
=> Corrected a typo in CSS section

README.md
Figured I'd take a crack at answering some of these questions.  I didn't see a contributor's guide, but I tried to keep my work consistent with what was already there.
Hope this helps.  Let me know if I should make any changes.
=> Added answers for a few sections

README-kr.md
add my github,
HTML question start
=> Today total translation KR

README.md
I believe this is a typo unless I'm really not understanding it 😅
=> Remove unnecessary word

questions/css-questions.md, questions/html-questions.md, questions/javascript-questions.md
Question anchor links were broken after I introduced [↑] into them. Changed it such that the back to top links are below the question.
=> Fix questions anchor links

questions/javascript-questions.md
Hi, 
There was an error in the example result in the spread vs rest code
=> copy edit of javascript questions

questions/javascript-questions.md
Browser devtools extension for debugging Vue.js applications.
=> Added Vue devtools to debugging section

translations/tl_PH/README.md
File Changes : 
README.md
Location : https://github.com/yangshun/front-end-interview-handbook/edit/master/translations/tl_PH/README.md
=> tl_PH Tagalog Localization #2 [230 Words]

translations/zh-cn/questions/css-questions.md, translations/zh-cn/questions/html-questions.md
Is PR the only way to contribute now?
=> Add zh-cn css part and fix some wording

translations/zh-cn/questions/javascript-questions.md
@HaitianLiu   
Wait for your review comment.
=> Add Chinese: update some of javascript questions

Translations/Tagalog/README.md, Translations/Tagalog/questions/css-questions.md
An update for css-questions.md file in Tagalog repo
I saw you made changes in the repository . I like it
=> Tagalog Localization

Translations/Portuguese-ptpt/README.md
Hello, I translated this file into Portuguese from Portugal..
I also created a new folder for Portuguese from Portugal translations (ptpt), to make it easier for contributors.
Please let me know if what I've done is alright.
Greetings!
=> Translation to Portuguese from Portugal ptpt of the file: README.md

Translations/Tagalog/questions/css-questions.md
Line 145 to Line 333
added translated @media answers
We typically do not accept submissions for new questions. This is because the [original questions repository](https://github.com/h5bp/Front-end-Developer-Interview-Questions) has been curated by a team of industry professionals and we use it as ground truth and keep our answers in sync with the questions/answers as much as possible. If you are keen to add a question/answer, firstly try to submit an issue/pull request to that repository, once your question is merged, you can then make a pull request with your answers to this repository.
You are welcome to make improvements to existing answers and/or answer unanswered questions. Try to add a list of references you used when arriving at the answers or any supplementary material that might …
=> Tagalog Localization #3

Translations/Tagalog/questions/css-questions.md
Completed css-questions.md. Thanks
=> Tagalog Localization #4 [1341 WORDS]

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Comment out PR and Issue template in case contributors don't remove them
=> Comment out template

Translations/Tagalog/questions/html-questions.md
File : **html-questions.md** 
Location Translation/Tagalog/questions/html-questions.md
_Completion Rate : ~33%_
Total Word Count : [1067 WORDS]
=> Tagalog Localization #5

questions/html-questions.md
=> [HTML] Answer srcset question

Translations/Tagalog/questions/javascript-questions.md
File : javascipt-questions.md
Source Language : English 
Translates Language: Tagalog
Completion Rate : ~15%
Location : Translations/Tagalog/questions/javascript-questons.md
Total Translated words : 1102 WORDS
=> Tagalog Localization #7 - javascript-questions.md

CONTRIBUTING.md, README.md, questions/css-questions.md, questions/html-questions.md, questions/javascript-questions.md
Fix grammar in all content using Grammarly.
=> Better grammar

Translations/Tagalog/questions/javascript-questions.md
File : js-questions.md
Completion Rate 20%
File : Translations/Tagalog/questions/js-questions.md
Word Count : [560 Words]
=> Tagalog localization #8 - js-questions

questions/javascript-questions.md
IIFE answer has been extended with `void` operator,
=> JS > IIFE answer extended

Translations/Chinese/questions/css-questions.md
=> fix wrong format

Translations/Japanese/README.md, Translations/Japanese/questions/css-questions.md, Translations/Japanese/questions/html-questions.md, Translations/Japanese/questions/javascript-questions.md
Add javascript-questions.md and keep up with new answers.
But this is just a really rough translation, so this needs more improvements.
I will do that!
=> Complete Japanese Translation

Translations/Tagalog/questions/javascript-questions.md
File : js-questions.md
Location : Translations/Tagalog/questions/javascript-questions.md
Completion rate : 70%
Total Word Count translated in this PR : 2,267 Words
Untranslated Words : About 3,400 Words
=> Partial javascript-questions.md Tagalog Localization [70%]

questions/css-questions.md
- Re-structured a sentence
- Changed "takes up" to "occupies" to be more concise
=> Re-structure sentence in translate vs abs. pos.

questions/javascript-questions.md
Flux is not based on react/redux and flux pattern does not encourage functional programming.
=> Clarify flux architecture

Translations/Chinese/questions/javascript-questions.md
Fix wrong markdown and add a patch on javascript translation.
Please review this pull request.
=> Fix wrong markdown & add a patch

Translations/Chinese/README.md, Translations/Chinese/questions/javascript-questions.md
=> Update part of zh-cn content

Translations/Korean/README.md
=> Upadate README.md

questions/javascript-questions.md
=> Answer "What are the differences between ES6 class and ES5 function constructors?"

CONTRIBUTING.md
To help readers understand better and improve readability.
=> Edited for clarity and concision

questions/css-questions.md
The question:
> What does `* { box-sizing: border-box; }` do? What are its advantages?
is actually 2 questions and in my opinion only the first one is answered. I tried to answer the second one, plus I used a reference post from Paul Irish.
=> Improve an answer to the box model question

questions/css-questions.md
=> Improve question about "retina graphics"

questions/css-questions.md
I'm answering this question:
> Can you explain the difference between coding a website to be responsive versus using a mobile-first strategy?
Although I wonder if the question should actually be:
> Can you explain the difference between coding a website to be responsive versus using a mobile-_**specific**_ site strategy?
... which is a completely different question.
=> Complete TODO missing answer about responsive vs mobile-first

Translations/Korean/questions/javascript-questions.md
Korean Translation: 5 JS questions
=> Korean Translation: 5 JS questions

Translations/Korean/questions/css-questions.md
Translate 5 css-questions in korea
=> Translate 5 css-questions

questions/css-questions.md
I saw this question was still unanswered and added a proper answer to it. Also added a reference link for deeper insights to the topic. This is my first contribution to an open repository.
=> Answer "Are you familiar with styling SVG?" question

questions/css-questions.md
=> Added link of responsive vs adaptive design qn 

questions/javascript-questions.md
Hi, there. Thanks a million for putting this helpful repo together! 
Here's a small formatting fix. I'll also make some pull requests tackling some TODOs later 👍
=> Fix formatting issue in JS questions

questions/css-questions.md
=>  Fix a Typo on a question title and anchor

questions/html-questions.md
English is not my native language so feel free to tell me if there is any mistake
=> fix(html): better explanation for DOCTYPE

Translations/Chinese/questions/css-questions.md
=> add chinese translation

questions/html-questions.md
Line 24. Changed from "declation" to "declaration".
=> spelling fix

questions/javascript-questions.md
=> Answers an arrow function use case question

questions/javascript-questions.md
This pull request updates the answer to this question: [What language constructions do you use for iterating over object properties and array items?](https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#what-language-constructions-do-you-use-for-iterating-over-object-properties-and-array-items)
The previous answer mentions `for` loops and `forEach` as two ways to iterate arrays. I have included `for-of` loops, which were introduced in ES6. I have also updated the pros and cons/use cases of all three methods.
=> [JS] Update answer about ways to iterate arrays

questions/javascript-questions.md
I've added an answer for the question "ES6 Template Literals offer a lot of flexibility in generating strings, can you give an example?"
The two use cases I gave were to help do string interpolation and to help create multi-line strings. The MDN reference I included also has a few more good examples for other use cases that people can check out.
=> [JS] Answer template literal question

questions/javascript-questions.md
Included information about *function expressions*
=> [JS] Update IIFE answer

Translations/Japanese/questions/javascript-questions.md
I updated Japanese translation!
- fix markdown link
- fix Japanese grammar
- add new Japanese translation
=> Update Japanese translation

questions/javascript-questions.md
I added an answer for the question: "What advantage is there for using the arrow syntax for a method in a constructor?" and provided two references, one from MDN for a more general overview of arrow functions and one from a Medium article that outlines a use-case in React class components.
=> [JS] Answer arrow function in constructor method question

Translations/Japanese/questions/css-questions.md
I updated the Japanese translation!
=> [CSS] Update Japanese translation

Translations/Korean/questions/javascript-questions.md
attribute와 property 모두 속성이라고만 명시돼있어 구분할 수가 없어 명시해주었습니다.
=> [JS] attribute, property 구분해서 명시

questions/javascript-questions.md
Denoted "this" as code by using double tick mark for clarity.
=> [JS] Update "Explain Function.prototype.bind" part

README.md, Translations/Korean/README.md
- Add link name for Korean readers.
- Sync with main README (Add Support part)
- Improve Korean translation in Korean README
=> Update README & Korean README

Translations/Korean/questions/html-questions.md
- Sync HTML questions in Korean.
- Improve translation.
=> Update: Sync Korean HTML questions with master.

questions/javascript-questions.md
=> [JS] Fix typo

questions/css-questions.md, questions/javascript-questions.md
=> [JS] Add hoist link to function declaration/expression section

Translations/Chinese/questions/css-questions.md, Translations/Chinese/questions/html-questions.md, Translations/Chinese/questions/javascript-questions.md, Translations/Japanese/questions/css-questions.md, Translations/Japanese/questions/html-questions.md, Translations/Japanese/questions/javascript-questions.md, Translations/Portuguese/questions/html-questions.md, Translations/Tagalog/questions/css-questions.md, Translations/Tagalog/questions/html-questions.md, Translations/Tagalog/questions/javascript-questions.md, questions/css-questions.md, questions/html-questions.md, questions/javascript-questions.md
=> [Misc] Update links to the original repo with questions

Translations/Korean/questions/javascript-questions.md
- Sync JS questions in Korean.
- Improve translations.
SYNC HTML/CSS/JS ALL DONE!
=> Update: Sync Korean JS questions.

questions/html-questions.md
…meworks as Selenium without messing up the semantics of the overall html markup.
I think having a valid usage for data attributes balances this out. I've been at several companies that use this for Selenium / Capybara hooks and I think it's probably still the best way.
=> [HTML] Provides a valid case for using data attributes - testing

questions/html-questions.md
I believe it's important to point out that local/session store, and cookies may be invalidated by the user, especially since it always has to be considered as a possibility when deciding how to approach local persistence of data.
=> [HTML] Point out that local/session store, and cookies may be invalidated by user

questions/javascript-questions.md
=> [JS] Code organization typo fix

questions/javascript-questions.md
Added answer to JavaScript section
=> [JS] Answer immutability questions

questions/css-questions.md
Link out to the rules for what exactly causes a stacking context to happen in the first place.
=> [CSS] What exactly causes a stacking context?

questions/css-questions.md
While I think Babel takes us out of vanilla front end stack, I think at this point, if you're looking for a job as a front end developer, you probably need to at least be aware of these sorts of options :)
You work at FB? I'm curious, do you think they would ask front end candidates a lot of data structures and algorithm questions? I assume so, but I read somewhere recently that this isn't always expected of candidates at certain places if you're not going for full stack which sort of surprised me. I'm a self taught programmer of 15 years, so I'm good, but don't have CS formal training so I always have to brush up on this haha.
=> [HTML] Mention Postcss as a reasonable way to fix cross-browser styling issues

questions/css-questions.md
=> [CSS] Add a link related to CSS properties triggering

questions/css-questions.md
Adds another disadvantage to using a css preprocessor. This was actually exactly why our company is deciding to remove Sass in favor of using CSS via postcss plugins.
=> [CSS] More answers to advantages/disadvantages of using CSS preprocessors

questions/javascript-questions.md
Answers the second part of question from the h5bp version:
I happened to just run in to this issue doing a large refactor/upgrade :)
=> [JS] Answer the second part of "this" question

questions/css-questions.md
Point out the potential issues between responsive and adaptive design.
=> [CSS] Point out the potential issues between responsive and adaptive design

questions/javascript-questions.md
I believe you were referring to the parentheses () not brackets {}.
=> [JS] change parentheses/brackets

questions/javascript-questions.md
Adds the simplest examples of prototypal inheritance I could come up with.
=> Simplest examples of prototypal inheritance possible

Translations/Chinese/questions/javascript-questions.md
Update Chinese javascript questions translation
=> feat:update Chinese javascript questions translation

Translations/Chinese/questions/css-questions.md
=> [CSS][Chinese] Answer questions on media queries

questions/javascript-questions.md
=> [JS] Add duplicate function with ES6 Syntax

questions/css-questions.md
=> [css] add CSS display property explanations

questions/javascript-questions.md
add the pros and cons of immutability
=> [js] answer the pros and cons of immutability

questions/css-questions.md
=> [css] fix typo 'gird' to 'grid'

README.md
=> misc: add a link to Russian translation in the main README

questions/css-questions.md, questions/html-questions.md, questions/javascript-questions.md
=> [fix] correction of redirect links on /questions

contents/en/css-questions.md, contents/zh/css-questions.md
=> [css][en] added a translation from its CN version

contents/en/html-questions.md
=> contents(html): add important missing information on hreflang

contents/en/html-questions.md
=> contents(html): typo fixing and additional thoughts

contents/de/html-questions.md
German translation of HTML part. Pls. consider merging.
=> HTML german

contents/en/README.md, contents/es/README.md, contents/jp/README.md, contents/kr/README.md, contents/pl/README.md, contents/pr/README.md, contents/tl/README.md, contents/zh/README.md
- fix broken image links
- replaced rawgit links with local image reference
=> fix: image links

contents/es/javascript-questions.md
=> contents(js): Spanish translations of some JS questions

contents/en/css-questions.md
=> css: fix typo

contents/jp/javascript-questions.md
For some questions, English answers existed, but the Japanese answers were not translated.
memo:
This project has helped me in my learning. Thanks!😊
=> contents(js): Japanese translations of some JS empty answer

contents/pr/css-questions.md
At the moment I did the translation of just three questions to check if my pull request will be accepted. If accepted, I will be translating the rest when I have free time.
=> css: translate for pr language

contents/pr/css-questions.md, website/yarn.lock
add some more css questions translateds to pr.
=> css: add more pr translations

contents/pr/html-questions.md
This PR is just to translate a little lost text in english to pt 😊
Congratz for this project! 🥳
=> docs: translate HTML text to pt

contents/kr/html-questions.md
I fixed a Korean typo and broken markdown.
=> contents: fix typo in Korean

contents/en/css-questions.md
Thank you for this repo, it's really helpful. I have added `grid` and `inline-grid` for the CSS display attribute of the BFC.
=> contents(css): add `grid` and `inline-grid` for BCF

contents/pop-quiz.md
Sorry for the grammar police. Thank you for the content!
=> contents: small grammatical tweak

website/blog/2021-12-23-front-end-vs-back-end-system-design-interviews.md
=> blog: add post on front end vs. back end system design

contents/javascript-questions.md
"an exception" is missing in:
- Makes attempts to delete undeletable properties throw an exception (where before the attempt would simply have no effect).
=> contents(js): update use strict answer

contents/javascript-questions.md
=> fix: typo in javascript trivia

website/docusaurus.config.js, website/src/pages/index.js
Fixed Edit this page and open pull request links by changing branch from master to main in repo links.
=> website: fix edit this page and open pull request link

contents/css-questions.md
=> contents(css): fix typo in responsive vs mobile-first question

contents/javascript-questions.md
=> contents(js): fix typo in ImmutableJS

contents/css-questions.md
=> contents(css): fix pseudo element syntax

contents/front-end-system-design-ui-components.md
I noticed a couple of mistakes in the English translation of the design UI comp. page. With this pull request, I am proposing a few improvements to the translation.
=> contents(sd): improved English translation of the design UI components page

packages/quiz/questions/describe-the-difference-between-a-cookie-sessionstorage-and-localstorage/en-US.mdx
Add more details that specifically answer the question about differences for the different storage methods.
=> qns(js): describe different storage methods

packages/quiz/questions/whats-the-difference-between-resetting-and-normalizing-css-which-would-you-choose-and-why/en-US.mdx
=> quiz(css): fix typo in difference between resetting and normalizing css

packages/quiz/questions/describe-what-you-like-and-dislike-about-the-css-preprocessors-you-have-used/en-US.mdx
…essors-you-have-used" question
=> quiz(css): fix typo in css preprocessors

packages/quiz/questions/how-is-responsive-design-different-from-adaptive-design/en-US.mdx
=> quiz(html): fix typo

packages/quiz/questions/what-is-event-loop-what-is-the-difference-between-call-stack-and-task-queue/en-US.mdx
Link another resource source for event loop.
=> qns(quiz): add another source for event loop

README.md
change "Twitter" to "X (Twitter)"
This fixes https://github.com/yangshun/front-end-interview-handbook/issues/395
=> misc: change "Twitter" to "X (Twitter)"

packages/quiz/questions/whats-the-difference-between-call-and-apply/zh-CN.mdx
=> quiz: fix typo in `.apply`

packages/quiz/questions/what-language-constructions-do-you-use-for-iterating-over-object-properties-and-array-items/en-US.mdx
=> quiz: fix typo

packages/quiz/questions/explain-how-prototypal-inheritance-works/en-US.mdx
Fixed an incorrect output display
=> fix(quiz): prototypal inheritance output

packages/quiz/questions/what-is-the-definition-of-a-higher-order-function/en-US.mdx
Proposing a small copy change. Originally, I only wanted to suggest appending `'s` to `Let` but then thought the sentence could be a bit clearer with a couple more changes.
=> qns(js): update higher order function

contents/javascript-questions.md
=> misc: remove TODO from javascript-questions.md

packages/behavioral-interview-guidebook/contents/overview/en-US.mdx
change 'understated' to 'overstated' to more accurately reflect the significance of behavioral interviews.
=> big(fix): change typo in importance

packages/quiz/questions/what-does-box-sizing-border-box-do-what-are-its-advantages/zh-CN.mdx
=> docs: update the content error

packages/quiz/questions/is-there-any-reason-youd-want-to-use-translate-instead-of-absolute-positioning-or-vice-versa-and-why/zh-CN.mdx
=> docs: improve wording and flow in documentation

packages/quiz/questions/describe-block-formatting-context-bfc-and-how-it-works/zh-CN.mdx
=> docs: update the docs into more appropiate way

packages/quiz/questions/designing-or-developing-for-multilingual-sites/zh-CN.mdx
=> docs: update the docs's link error

packages/quiz/questions/explain-how-jsonp-works-and-how-its-not-really-ajax/zh-CN.mdx
=> docs: improve the docs translation.

packages/quiz/questions/what-are-data-attributes-good-for/zh-CN.mdx
=> docs: improve content accuracy

packages/quiz/questions/describe-what-you-like-and-dislike-about-the-css-preprocessors-you-have-used/zh-CN.mdx
=> docs: fix the link

contents/javascript-questions.md
Corrected the question phrasing from "Why you might want to create static class members?" to "Why might you want to create static class members?" for grammatical accuracy.
=> fix(typo): Fix typo error in JavaScript static class members question

packages/behavioral-interview-guidebook/contents/questions-to-ask/en-US.mdx
closes greatfrontend/greatfrontend#94
=> [behavioral-interview-guidebook] Fix typo

packages/front-end-interview-guidebook/contents/quiz/en-US.mdx
-----
<a href="https://stackblitz.com/~/github.com/feilinlp/front-end-interview-handbook/tree/fl/content/typo"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/feilinlp/front-end-interview-handbook/tree/fl/content/typo)._
=> [quiz] Fix typo

contents/front-end-system-design-applications.md
=> contents(sd): add links to paid Video Streaming and Email Client system design materials

packages/quiz/questions/explain-hoisting/en-US.mdx
- Add more explanation about hoisting referencing ECMAScript specification
- Fix error text on `let` declaration
=> Add more explanation about hoisting

packages/quiz/questions/have-you-ever-worked-with-retina-graphics-if-so-when-and-what-techniques-did-you-use/en-US.mdx, packages/quiz/questions/have-you-ever-worked-with-retina-graphics-if-so-when-and-what-techniques-did-you-use/pt-BR.mdx, packages/quiz/questions/have-you-ever-worked-with-retina-graphics-if-so-when-and-what-techniques-did-you-use/zh-CN.mdx
After reading the quiz question on Greatfrontend
- https://www.greatfrontend.com/questions/quiz/have-you-ever-worked-with-retina-graphics-if-so-when-and-what-techniques-did-you-use 
I have noticed there was a pending reference to `Picturefill` polyfill, so I'm adding the reference.
=> contents(quiz): update retina graphics question with picturefill link

packages/quiz/questions/describe-event-bubbling/en-US.mdx, packages/quiz/questions/explain-event-delegation/en-US.mdx
Includes solution for JS quiz questions for-
- Event Bubbling
- Event Delegation
=> quiz/js: update event bubbling and delegation quiz solution

packages/quiz/questions/difference-between-function-person-var-person-person-and-var-person-new-person/en-US.mdx
Update JS question solution for this https://www.greatfrontend.com/questions/quiz/difference-between-function-person-var-person-person-and-var-person-new-person
=> quiz/js: difference between function declaration, function call, and constructor call

packages/quiz/questions/whats-a-typical-use-case-for-anonymous-functions/en-US.mdx
Update JS solution for this question https://www.greatfrontend.com/questions/quiz/whats-a-typical-use-case-for-anonymous-functions
=> quiz/js: use case for anonymous functions

packages/quiz/questions/whats-the-difference-between-a-variable-that-is-null-undefined-or-undeclared-how-would-you-go-about-checking-for-any-of-these-states/en-US.mdx
Update solution for JS question 
https://www.greatfrontend.com/questions/quiz/whats-the-difference-between-a-variable-that-is-null-undefined-or-undeclared-how-would-you-go-about-checking-for-any-of-these-states
=> quiz/js: difference between null, undefined and undeclared

packages/quiz/questions/whats-the-difference-between-call-and-apply/en-US.mdx
Update JS solution for question https://www.greatfrontend.com/questions/quiz/whats-the-difference-between-call-and-apply
=> quiz/js: difference between .call and .apply

packages/quiz/questions/what-are-the-benefits-of-using-spread-syntax-and-how-is-it-different-from-rest-syntax/en-US.mdx
Update JS solution for the questionhttps://www.greatfrontend.com/questions/quiz/what-are-the-benefits-of-using-spread-syntax-and-how-is-it-different-from-rest-syntax
=> quiz/js: spread and rest syntax

packages/quiz/questions/why-you-might-want-to-create-static-class-members/en-US.mdx
Update the JS solution for https://www.greatfrontend.com/questions/quiz/why-you-might-want-to-create-static-class-members
=> quiz/js: update static class members solution

packages/quiz/questions/explain-how-prototypal-inheritance-works/en-US.mdx, packages/quiz/questions/what-advantage-is-there-for-using-the-arrow-syntax-for-a-method-in-a-constructor/en-US.mdx
This change will improve following js quiz: 
* Prototypical inheritance 
* Arrow functions
=> quiz/js: prototypical inheritance and arrow function

packages/quiz/questions/what-are-the-differences-between-es6-class-and-es5-function-constructors/en-US.mdx, packages/quiz/questions/what-is-a-closure-and-how-why-would-you-use-one/en-US.mdx
This change includes update for following
* ES6 class vs ES5 function constructor
* Closures in javascript
=> quiz/js: closure and es6 class vs es5 function constructor

packages/quiz/questions/what-is-use-strict-what-are-the-advantages-and-disadvantages-to-using-it/en-US.mdx, packages/quiz/questions/what-language-constructs-do-you-use-for-iterating-over-object-properties-and-array-items/en-US.mdx
This change will update following: 
* Strict mode 
* Iterating over array and object properties
=> quiz/js:  strict mode and iterating over array and object

packages/quiz/questions/explain-the-differences-on-the-usage-of-foo-between-function-foo-and-var-foo-function/en-US.mdx
Update JS solution for the question https://www.greatfrontend.com/questions/quiz/explain-the-differences-on-the-usage-of-foo-between-function-foo-and-var-foo-function
=> quiz/js: update js solution for usage of function declaration and expression

packages/quiz/questions/what-are-the-pros-and-cons-of-using-promises-instead-of-callbacks/en-US.mdx
Update JS solution for question https://www.greatfrontend.com/questions/quiz/what-are-the-pros-and-cons-of-using-promises-instead-of-callbacks
=> quiz/js: pros and cons of using Promises instead of callbacks

packages/quiz/questions/explain-the-difference-between-mutable-and-immutable-objects/en-US.mdx
Update JS solution for the question https://www.greatfrontend.com/questions/quiz/explain-the-difference-between-mutable-and-immutable-objects
=> quiz/js: update mutable and immutable objects js solution

packages/quiz/questions/whats-the-difference-between-a-relative-fixed-absolute-and-statically-positioned-element/en-US.mdx
https://www.greatfrontend.com/questions/quiz/whats-the-difference-between-a-relative-fixed-absolute-and-statically-positioned-element
=> quiz/css: add sticky to the question title

packages/quiz/questions/explain-the-differences-between-commonjs-modules-and-es-modules/en-US.mdx, packages/quiz/questions/explain-the-differences-between-commonjs-modules-and-es-modules/metadata.json, packages/quiz/questions/what-are-polyfills-for/en-US.mdx, packages/quiz/questions/what-are-polyfills-for/metadata.json
This change will add answers for following
* What are polyfills used for 
* CommonJS vs ES modules in Javascript
=> quiz/js:  polyfills and commonjs vs es modules in javascript

packages/quiz/questions/explain-the-difference-between-synchronous-and-asynchronous-functions/en-US.mdx
This change will add details comparing following 
* Synchronous functions
* Asynchronous functions
* Web workers
=> js/quiz: details about async functions, sync functions and web workers

packages/quiz/questions/what-are-microtasks-and-macrotasks/en-US.mdx, packages/quiz/questions/what-are-microtasks-and-macrotasks/metadata.json, packages/quiz/questions/what-are-workers-in-javascript-used-for/en-US.mdx, packages/quiz/questions/what-are-workers-in-javascript-used-for/metadata.json
This change will add answers for following quizzes
* Workers in JavaScript
* Micro and macro tasks in Javascript
=> js/quiz: workers, micro and macro tasks

packages/quiz/questions/explain-ajax-in-as-much-detail-as-possible/en-US.mdx
Update JS solution for the question https://www.greatfrontend.com/questions/quiz/explain-ajax-in-as-much-detail-as-possible
=> quiz/js: update explain ajax solution

packages/quiz/questions/what-are-the-advantages-and-disadvantages-of-using-ajax/en-US.mdx
Update JS solution for the question https://www.greatfrontend.com/questions/quiz/what-are-the-advantages-and-disadvantages-of-using-ajax
=> quiz/js: update js solution for advantage & disadvantages of ajax

packages/quiz/questions/how-does-garbage-collection-in-the-context-of-javascript-work/en-US.mdx, packages/quiz/questions/how-does-garbage-collection-in-the-context-of-javascript-work/metadata.json, packages/quiz/questions/what-are-iterators-and-generators-and-what-are-they-used-for/en-US.mdx, packages/quiz/questions/what-are-iterators-and-generators-and-what-are-they-used-for/metadata.json
This change will add answers for following
* Iterator and generators in JavaScript
* Garbage collection in JavaScript
=> quiz/js: iterator, generator and garbage collection in javascript

packages/quiz/questions/what-are-server-sent-events/en-US.mdx, packages/quiz/questions/what-are-server-sent-events/metadata.json
This change will add answer for Server-sent events in JavaScript
=> quiz/js: server-sent events in javascript

contents/companies/google-front-end-interview-questions.md
Update "Practice Question" for paid member link under Google Interview Questions >> User interface coding 
Current URL pointing to : https://www.greatfrontend.com/questions/javascript/generate-table?utm_source=frontendinterviewhandbook&utm_medium=referral&gnrs=frontendinterviewhandbook
Updated URL : https://www.greatfrontend.com/questions/user-interface/generate-table
=> contents: Updated broken link on google-front-end-interview-practice-question.md

packages/behavioral-interview-guidebook/contents/collaboration/en-US.mdx, packages/behavioral-interview-guidebook/contents/growth-mindset/en-US.mdx, packages/behavioral-interview-guidebook/contents/overview/en-US.mdx, packages/behavioral-interview-guidebook/contents/problem-solving/en-US.mdx, packages/behavioral-interview-guidebook/contents/questions-to-ask/en-US.mdx, packages/behavioral-interview-guidebook/contents/questions/en-US.mdx, packages/behavioral-interview-guidebook/contents/self-introduction/en-US.mdx, packages/behavioral-interview-guidebook/contents/why-work-here/en-US.mdx, packages/front-end-interview-guidebook/contents/algorithms/en-US.mdx, packages/front-end-interview-guidebook/contents/coding/en-US.mdx, packages/front-end-interview-guidebook/contents/javascript/en-US.mdx, packages/front-end-interview-guidebook/contents/overview/en-US.mdx, packages/front-end-interview-guidebook/contents/quiz/en-US.mdx, packages/front-end-interview-guidebook/contents/resume/en-US.mdx, packages/front-end-interview-guidebook/contents/system-design/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface-components-api-design-principles/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface-questions-cheatsheet/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface/en-US.mdx, packages/system-design/contents/cheatsheet/en-US.mdx, packages/system-design/contents/common-mistakes/en-US.mdx, packages/system-design/contents/evaluation-axes/en-US.mdx, packages/system-design/contents/framework/en-US.mdx, packages/system-design/contents/introduction/en-US.mdx, packages/system-design/contents/types-of-questions/en-US.mdx
- Add new SEO related title and description
- Update existing page title and description which are displayed
=> contents: update guides front matter title and description

packages/behavioral-interview-guidebook/contents/collaboration/en-US.mdx, packages/behavioral-interview-guidebook/contents/growth-mindset/en-US.mdx, packages/behavioral-interview-guidebook/contents/overview/en-US.mdx, packages/behavioral-interview-guidebook/contents/problem-solving/en-US.mdx, packages/behavioral-interview-guidebook/contents/questions-to-ask/en-US.mdx, packages/behavioral-interview-guidebook/contents/questions/en-US.mdx, packages/behavioral-interview-guidebook/contents/self-introduction/en-US.mdx, packages/behavioral-interview-guidebook/contents/why-work-here/en-US.mdx, packages/front-end-interview-guidebook/contents/algorithms/en-US.mdx, packages/front-end-interview-guidebook/contents/coding/en-US.mdx, packages/front-end-interview-guidebook/contents/javascript/en-US.mdx, packages/front-end-interview-guidebook/contents/overview/en-US.mdx, packages/front-end-interview-guidebook/contents/quiz/en-US.mdx, packages/front-end-interview-guidebook/contents/resume/en-US.mdx, packages/front-end-interview-guidebook/contents/system-design/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface-components-api-design-principles/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface-questions-cheatsheet/en-US.mdx, packages/front-end-interview-guidebook/contents/user-interface/en-US.mdx, packages/system-design/contents/common-mistakes/en-US.mdx, packages/system-design/contents/evaluation-axes/en-US.mdx, packages/system-design/contents/framework/en-US.mdx, packages/system-design/contents/introduction/en-US.mdx, packages/system-design/contents/types-of-questions/en-US.mdx
Please take note that this changes reflect the guide name changes from `Guide` to `Playbook`.  
I am not sure when we are going to prod with this new name. Please merge accordingly
=> contents: update seo frontmatter based on the guide renamed

packages/quiz/questions/designing-or-developing-for-multilingual-sites/en-US.mdx
=> contents(quiz): servers select the locale

packages/quiz/questions/whats-the-difference-between-inline-and-inline-block/en-US.mdx
=> quiz/css: add block to the question title

packages/front-end-interview-guidebook/contents/algorithms/zh-CN.mdx, packages/front-end-interview-guidebook/contents/coding/zh-CN.mdx, packages/front-end-interview-guidebook/contents/javascript/zh-CN.mdx, packages/front-end-interview-guidebook/contents/overview/zh-CN.mdx, packages/front-end-interview-guidebook/contents/quiz/zh-CN.mdx, packages/front-end-interview-guidebook/contents/system-design/zh-CN.mdx, packages/front-end-interview-guidebook/contents/user-interface-components-api-design-principles/zh-CN.mdx, packages/front-end-interview-guidebook/contents/user-interface-questions-cheatsheet/zh-CN.mdx, packages/front-end-interview-guidebook/contents/user-interface/zh-CN.mdx
- I updated and replaced broken links inside zh-CN mdx files of frontend interview playbook
=> contents(zh-CN): update and replace broken links for frontend interview playbook

packages/front-end-interview-guidebook/contents/algorithms/pt-BR.mdx, packages/front-end-interview-guidebook/contents/coding/pt-BR.mdx, packages/front-end-interview-guidebook/contents/javascript/pt-BR.mdx, packages/front-end-interview-guidebook/contents/overview/pt-BR.mdx, packages/front-end-interview-guidebook/contents/quiz/pt-BR.mdx, packages/front-end-interview-guidebook/contents/system-design/pt-BR.mdx, packages/front-end-interview-guidebook/contents/user-interface-components-api-design-principles/pt-BR.mdx, packages/front-end-interview-guidebook/contents/user-interface-questions-cheatsheet/pt-BR.mdx, packages/front-end-interview-guidebook/contents/user-interface/pt-BR.mdx
- I updated and replaced broken links with correct ones in pt-BR files of frontend interview playbook
=> contents(pt-BR): update and replace broken links of frontend interview playbook

packages/quiz/questions/describe-block-formatting-context-bfc-and-how-it-works/en-US.mdx, packages/quiz/questions/explain-your-understanding-of-the-box-model-and-how-you-would-tell-the-browser-in-css-to-render-your-layout-in-different-box-models/en-US.mdx, packages/quiz/questions/have-you-played-around-with-the-new-css-flexbox-or-grid-specs/en-US.mdx, packages/quiz/questions/what-is-the-css-display-property-and-can-you-give-a-few-examples-of-its-use/en-US.mdx
Addressed quiz questions' user feedback.
Each commit is labelled with an id pointing to the User Feedback google sheet.
=> qns/quiz: address user feedback

packages/front-end-interview-guidebook/contents/user-interface-components-api-design-principles/en-US.mdx
Small grammar fixes for user-interface-components-api-design-principles
=> Grammar fixes en-US.mdx

contents/companies/airbnb-front-end-interview-questions.md
Added company user experiences for Airbnb from Discord
=> [feih] companies/airbnb: add GFE user experiences

contents/companies/apple-front-end-interview-questions.md
Added company user experiences for Apple from Discord
=> [feih] companies/apple: add GFE user experiences

contents/companies/bytedance-tiktok-front-end-interview-questions.md
Added company user experiences for ByteDance/TikTok from Discord
=> [feih] companies/bytedance-tiktok: add GFE user experiences

contents/companies/dropbox-front-end-interview-questions.md
Added company user experiences for Dropbox from Discord
Managed to only source 1 experience for Dropbox
=> [feih] companies/dropbox: add GFE user experiences

contents/companies/linkedin-front-end-interview-questions.md
Added company user experiences for LinkedIn from Discord
Only managed to source 4 experiences and they mainly come from the #interview-experiences channel.
=> [feih] companies/linkedin: add GFE user experiences

contents/companies/lyft-front-end-interview-questions.md
Added company user experiences for Lyft from Discord
Only managed to source 3 experiences and they mainly come from the #interview-experiences channel.
**Special Notes**:
1) not sure if emojis work here
2) added reference messages in ( ) to provide better context for messages, let me know if this works
Thanks!
=> [feih] companies/lyft: add GFE user experiences

contents/companies/microsoft-front-end-interview-questions.md
Added company user experiences for Microsoft from Discord
=> [feih] companies/microsoft: add GFE user experiences

contents/companies/twitter-front-end-interview-questions.md
Added company user experiences for Twitter/X from Discord
Only managed to source 2 experiences and they mainly come from the #interview-experiences channel.
=> [feih] companies/twitter: add GFE user experiences

contents/companies/uber-front-end-interview-questions.md
Added company user experiences for Uber from Discord
=> [feih] companies/uber: add GFE user experiences

contents/companies/reddit-front-end-interview-questions.md, contents/introduction.md, website/sidebars.js
Created new page and added company user experiences for Reddit from Discord.
Added references in sidebar to new Reddit page.
Only managed to source 3 experiences and they mainly come from the #interview-experiences channel.
=> [feih] companies/reddit: add GFE user experiences

contents/companies/oracle-front-end-interview-questions.md, website/sidebars.js
Created new page and added company user experiences for Oracle from Discord.
Added references in sidebar to new Oracle page.
Only managed to source 1 experiences and they mainly come from the #interview-experiences channel.
=> [feih] companies/oracle: add GFE user experiences

contents/companies/palantir-front-end-interview-questions.md
There was an issue with including <= in markdown  for one of the Palantir experiences
Rectified by escaping it
=> [feih] companies/palantir: fix markdown issue

website/docusaurus.config.js
=> [feih] seo: fix missing alt text issue

packages/react-interview-playbook/contents/react-landscape-history/en-US.mdx
Fix external 4XXs error from React Interview Playbook
=> [rip] seo: fix external 4XXs

packages/front-end-interview-guidebook/contents/javascript/en-US.mdx
Marketing team wants to add back links our JS questions repo.
This PR embed JS repo link into Javascript related content
=> [feih] seo: embed JS repo link in Javascript content
